config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :conversations, only: [:index, :new, :create, :show] do
    resources :messages, only: [:new, :create] do
    end
  end

  get '/conversations/:conversation_id/messages/:message_id/thoughts/new', to: 'thoughts#new'
  post '/conversations/:conversation_id/messages/:message_id/thoughts', to: 'thoughts#create'

  get '/search', to: 'conversations#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  has_many :thoughts
end

app/models/thought.rb
class Thought < ApplicationRecord
  belongs_to :message
end

app/models/user.rb
class User < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def index
    @conversations = Conversation.all
  end

  def create
    conversation = Conversation.create(title: params[:title], start_date: Time.now)

    redirect_to conversations_path
  end

  def show
    @conversation = Conversation.find(params[:id])
  end

  def search
    @conversations = Conversation.where("lower(title) like ?", "%#{params[:title].downcase}%")
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @conversation = Conversation.find(params[:conversation_id])
  end

  def create
    conversation = Conversation.find(params[:conversation_id])

    conversation.messages.create(text: params[:text], date_time_sent: Time.now)

    redirect_to conversation_path(params[:conversation_id])
  end
end

app/controllers/thoughts_controller.rb
class ThoughtsController < ApplicationController
  def new
  end

  def create
    message = Message.find(params[:message_id])

    message.thoughts.create(text: params[:text], date_time_sent: Time.now)

    redirect_to conversation_path(params[:conversation_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/conversations/index.html.erb
<h1>Conversations</h1>

<%= link_to "Create a Conversation", new_conversation_path %><br>

<p>Search for a Conversation:</p>
<%= form_with url: '/search', method: :get do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <%= form.submit 'Submit' %>
<% end %>

<% if @conversations.count > 0 %>
  <h2>My Conversations</h2>
  <% @conversations.each do |conversation| %>
    <h3><%= link_to conversation.title, conversation_path(conversation.id) %></h3>
    <p><%= conversation.start_date.strftime("%d/%m/%Y") %></p>
  <% end %>
<% else %>
  <p>You currently have no conversations.</p>
<% end %>

app/views/conversations/new.html.erb
<h2>Create a New Conversation</h2>

<%= form_with url: conversations_path, method: :post do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <%= form.submit 'Create Conversation' %>
<% end %>

app/views/conversations/search.html.erb
<h1>Search Results</h1>

<ul>
  <% @conversations.each do |conversation| %>
    <li><%= link_to conversation.title, conversation_path(conversation.id) %></li>
  <% end %>
</ul>

app/views/conversations/show.html.erb
<h1><%= @conversation.title %></h1>

<p>Date Conversation began: <%= @conversation.start_date.strftime("%d/%m/%Y") %></p>

<%= link_to "Add a Message",  new_conversation_message_path(@conversation.id) %>

<% if @conversation.messages.count > 0 %>
  <h2>Messages from this Conversation</h2>

  <ul>
    <% @conversation.messages.each do |message| %>
      <li id="message-<%= message.id %>"><%= message.text %> (<%= message.date_time_sent.strftime("%I:%M %p") %>) <%= link_to 'Add a Thought', "/conversations/#{@conversation.id}/messages/#{message.id}/thoughts/new" %></li>
      <% if message.thoughts.count > 0 %>
        <ul>
          <% message.thoughts.each do |thought| %>
            <li><%= thought.text %></li>
          <% end %>
        </ul>
      <% end %>
    <% end %>
  </ul>
<% else %>
  <p>There are currently no messages in this conversation.</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RemeshConversations</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/new.html.erb
<h2>Create a New Message</h2>

<%= form_with url: conversation_messages_path(@conversation.id), method: :post do |form| %>
  <%= form.label :text %>
  <%= form.text_field :text %>
  <%= form.submit 'Create Message' %>
<% end %>

app/views/thoughts/new.html.erb
<h2>Create a New Thought</h2>

<%= form_with url: "/conversations/#{params[:conversation_id]}/messages/#{params[:message_id]}/thoughts", method: :post do |form| %>
  <%= form.label :text %>
  <%= form.text_field :text %>
  <%= form.submit 'Create Thought' %>
<% end %>